nombre = input("Ingrese su nombre completo: ")
telefono = input("Ingrese su número telefónico: ")
gmail = input("Ingrese su gmail: ")
print("Su nombre es: " + nombre)
print("Su teléfono es: " + telefono)
print("Su gmail es: " + gmail)
print(id(nombre))
print(id(telefono))
print(id(gmail))
