print("Hola Mundo te digo 'Hello'")
print(100 + 50)
print('100 + 50')
print('"Python Total" es super divertido')
print("Hola" + " " + "Leo")
print("Hola soy \"Leonel\"")
print("Esta es una linea\nY esta es otra linea")
print("\tEsta es la tercera linea")
print('This isn\'t a number')
print('Esta \\ es una barra invertida')
print("Línea 1\nLínea 2\nLinea 3")
print("A\tB\tC\nD\tE\tF\nG\tH\tI\n")
print("\tD\tE\tF")
print("\tG\tH\tI")
print("Barra Normal: /")
print("Barra Invertida: \\")
